# Generated by Django 5.1 on 2024-08-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp_delete_tempuser_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
