# Generated by Django 5.1 on 2024-08-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_email_otp_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='password',
        ),
    ]
